use_frameworks!

platform :ios, '9.0'

target 'FYTestKit_Example' do
  pod 'FYTestKit', :path => '../'

  target 'FYTestKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
